# frozen_string_literal: true

module RubyLLM
  # A class representing a file attachment that is an image generated by an LLM.
  class ImageAttachment < Attachment
    attr_reader :image, :content, :id, :reasoning_id

    def initialize(data:, mime_type:, model_id:, id: nil, reasoning_id: nil)
      super(nil, filename: nil)
      @image = Image.new(data:, mime_type:, model_id:)
      @content = Base64.strict_decode64(data)
      @mime_type = mime_type
      @id = id
      @reasoning_id = reasoning_id
    end

    def image?
      true
    end
  end
end
